### ISSUE TITLE
Could not unzip extension for install D:\Program Files\chromeDownloads\Automa-main.zip. Could not unzip extension for install.

### ISSUE THREAD

**Issue by carls96** [AutomaApp/automa#1076]
Why does the downloaded ZIP not load properly into Google Chrome

![123](https://user-images.githubusercontent.com/59246551/211497572-0c86b893-e96e-4344-9cdb-db9b4ea63807.png)

**Comment by Kholid060** [comment]
It's because that's not the extension file. To download the extension file, go to the [Releases page](https://github.com/AutomaApp/automa/releases/) and click the `automa-chrome-*.zip` or the `automa-firefox-*.zip` file.

![NVIDIA_Share_5HO49WOhoH](https://user-images.githubusercontent.com/22908993/211500291-83829fc8-339d-4ec7-a1ca-b0965423fccd.png)
