### ISSUE TITLE
loop executes only once using variables

### ISSUE THREAD

**Issue by n1xn** [AutomaApp/automa#1125]
**Describe the bug**

`$x("//a[@class='productlist__link']")` in Chrome console return `30` nodes. Looping this selector only executes the first run.

**To Reproduce**
![image](https://user-images.githubusercontent.com/30150915/214694079-1cd677bb-5529-46e2-876f-e6a4c4d43bd0.png)
![image](https://user-images.githubusercontent.com/30150915/214694764-05e683fa-c6ed-4c86-b878-2fba0fb2fb6e.png)
![image](https://user-images.githubusercontent.com/30150915/214694857-fa6d4f99-431b-448b-8fcf-7e5eaea381ae.png)

**Expected behavior**
Opening a tab for each node from the selector.

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - OS: mac 13.0.1
 - Browser: 108.0.5359.94 (Official Build) (x86_64)
 - Extension Version: 1.27.1

**Additional context**
May be wrong usage but the docs can't provide clear instructions for this issue.

**Comment by Kholid060** [comment]
It's because you haven't added a Loop Breakpoint block. See the documentation about [Looping](https://docs.automa.site/workflow/looping.html#using-the-loop-data-or-loop-elements-block) in Automa

**Comment by n1xn** [comment]
Unfortunately I actually did in the past. Just added it right now for the sake of demonstration, but I get the same error again.
![image](https://user-images.githubusercontent.com/30150915/214753133-c59c4533-fba1-47c9-af0d-3ec17c0e056d.png)
![image](https://user-images.githubusercontent.com/30150915/214753162-e70c0065-0452-49c1-9e40-bbaf76fee59f.png)

**Comment by Kholid060** [comment]
If the New Tab block on that workflow updates the tab where you loop the elements, it will throw that error because it will remove the attribute used to mark which element to loop. To fix this, you need to change the logic of the workflow by getting all the URLs first from the element and then looping those URLs.

If it opens a new tab, you need to switch the active tab where you loop elements using the Switch Tab block.

**Comment by n1xn** [comment]
@Kholid060 MVP.
