### ISSUE TITLE
Add support for entering Text inside editable div

### ISSUE THREAD

**Issue by xRajatDas** [AutomaApp/automa#1158]
The problem is that the automa does not provide any way to enter text inside an editable div while automating WhatsApp web.

I would like the automation tool "automa" to provide a way to enter text inside an editable div while automating WhatsApp web. This could be done using the send_keys() function of the Selenium WebDriver, which can send keystrokes to an element on a web page, including an editable div.

It is important to have the ability to enter text inside an editable div while automating WhatsApp web, as this is how users typically send messages on the platform. Without this feature, it is not possible to fully automate the process of sending messages, and users may need to manually enter messages, which defeats the purpose of automation.

**Comment by Kholid060** [comment]
You can actually do that by using the Forms or Press Key block and the [Debug mode](http://localhost:5173/workflow/debug-mode.html#debug-mode) is enabled in the block settings.

**Comment by kolampixel** [comment]
@Kholid060, issues for "contenteditable" div:

[contenteditable]>div>div>div>span>span

typing with keyboard must be like this...
![2023-03-30 08_19_33-Home _ Twitter and 11 more pages - Personal - Microsoft​ Edge](https://user-images.githubusercontent.com/121801559/228731746-7487e121-5520-4ccc-9249-cba68ff51607.png)

but, if use automa "forms block" or "press key block", with Debug mode disabled.

![2023-03-30 08_24_01-UI Vision RPA 8 3 1 - (Tab_ 验证码中间页)](https://user-images.githubusercontent.com/121801559/228731983-5ea1e1bd-7d4b-4b18-86b4-956aba86f731.png)

But if "Debug mode" is enabled, nothing happens.

**Comment by jvcss** [comment]
I'm trying to understand this engine and I found what can we call trigger 

```js
  async function typeText(element) {
    if (block.debugMode && data.type === 'text-field') {
      const commands = data.value.split('').map((char) => ({
        text: char,
        type: 'keyDown',
      }));
      const typeDelay = +block.data.delay;
      await sendMessage(
        'debugger:type',
        {
          commands,
          tabId: block.activeTabId,
          delay: Number.isNaN(typeDelay) ? 0 : typeDelay,
        },
        'background'
      );

      return;
    }

    markElement(element, block);
    await handleFormElement(element, data);
  }
```
and I was thinking how can we perform a loop for this element in such way as this `pressKeyWithCommand` in the handlerPressKey, because we are preforming a callback to the engine here in the message.js and I guess that this is the issue.


```js
export function sendMessage(name = '', data = {}, prefix = '') {
  let payload = {
    name: nameBuilder(prefix, name),
    data,
  };

  if (isFirefox) {
    payload = JSON.stringify(payload);
  }

  return browser.runtime.sendMessage(payload);
}
```


In the webextension-polyfill lib the definition of the runtime.Static.sendMessage method only send a single message,



 so I guess that could be a way to keep looping in the string send the same form multiple times kind of removing the first letter in each loop until finish the string. But I'm not too familiar with this js block


So my question and suggestion is there is a way to make a loop between blocks? like start with the form that will send the first letter then modify this globalData variable local instance (or copy) to keep sending this again and again?


like here, how can I keep looping in a form?

![example](https://user-images.githubusercontent.com/57873270/235344225-048ef66d-32cc-442a-8283-ce26a121a2e0.png)

**Comment by jakernel** [comment]
> You can actually do that by using the Forms or Press Key block and the [Debug mode](http://localhost:5173/workflow/debug-mode.html#debug-mode) is enabled in the block settings.
Is there a working example?

**Comment by sek-MiraiMinds** [comment]
@Kholid060 have you found any solution for this that how we can fix this ?

**Comment by ARajgor** [comment]
@Kholid060 It is working in debug mode but for the production or actual workflow debug is not a go-to way so how it working in debug mode but not in simple mode?

write the complete word with form block running in debug mode on
![image](https://github.com/AutomaApp/automa/assets/76404080/3321c57e-d7da-47e6-82e1-5d9f70f591a7)

write only one character of the word without running in debug mode
![image](https://github.com/AutomaApp/automa/assets/76404080/6030e366-56fe-454f-a99e-385653073a7b)
