### ISSUE TITLE
About Access Loop Item

### ISSUE THREAD

**Issue by yiuylee** [AutomaApp/automa#1291]
Hi I'm trying to use the loop function to type the different index to the website.
But when I try to get the data from the google sheet and I type that {{loopData.sppz3_.uuid}} into "forms" block but show "no data to show", but I can preview data in google sheets block.

how can I get the data

**Comment by WickedInvi** [comment]
Can you confirm that you have selected Google Sheets and passed the Reference Key (google sheet block ref) inside Loop Data Block?

For the Forms block make sure you get the correct loop ID it is case sensitive. 
Also I am not sure if this is required but I use @ instead of . before the loop ID
{{loopData.sppz3_.uuid}} ==> {{loopData@sppz3_.uuid}}
