### ISSUE TITLE
Extension disappeared (uninstalled?)

### ISSUE THREAD

**Issue by stanislavkozlovski** [AutomaApp/automa#1296]
Can anyone advise me on where the extension stores the locally-loaded workflows? I am pretty scared I lost all of them. I should have backed up

**Comment by Kholid060** [comment]
The workflow data is stored locally in the Chrome extension storage. If you uninstall the extension, you'll lose the data because Chrome will automatically all the data related to the extension. To prevent this, you can backup your workflows to the cloud or your computer by going to the settings and clicking the "Backup Workflows" section.

![image](https://github.com/AutomaApp/automa/assets/22908993/c3294948-8745-401e-867d-94f572957a50)
