### ISSUE TITLE
Trigger Automa's workflow through URL

### ISSUE THREAD

**Issue by wisinfun** [AutomaApp/automa#1607]
**Is your feature request related to a problem? Please describe.**
Triggering workflow through URLs can better integrate into computer workflow

**Describe the solution you'd like**
I see that each workflow in Automa has a corresponding URL, such as
 `chrome-extension://infppggnoaenmfagbfknfkancpbljcca/newtab.html#/workflows/PyhBPkFtxxxVseo1KdD`.
Can this workflow be run on this basis by using a suffix? It would be even better if external parameters could be passed through the URL, for example: 
`chrome-extension://infppggnoaenmfagbfknfkancpbljcca/newtab.html#/workflows/PyhBPkFtxxxVseo1KdD/run/?argument=test`

**Comment by gvs42** [comment]
I am not able to get any parameters/variables into the workflow execution as stated in the documentation. The URL in the documentation is:

**Comment by zzph** [comment]
I am in the same position, has anyone figured this out?

I tried many methods (as outlined here: https://docs.automa.site/workflow/variables.html)

**Comment by zzph** [comment]
I've found the problem, code needs to be updated:

Here, you are not correctly passing the search params from the URL: 
`https://github.com/AutomaApp/automa/commit/5f1caf11735e2b0c55c6418918a3932e900451b2#diff-411f1a3a9aae65d635492a191d9577c3fd8fdeeb0a7726f050ad04d1c65e3453R13`

Rather than doing this:
```
  searchParams.forEach((key, value) => {
    variables[key] = decodeURIComponent(value);
  });
  return { workflowId: workflowId ?? '', variables };
```

You can just do this:
```
  return { workflowId: workflowId ?? '', variables: Object.entries(searchParams) };
```

**Comment by Kholid060** [comment]
Fixed in v1.28.27

**Comment by marciofelipebr** [comment]
Tentei dessas duas  formas e não esta passando as variaveis, e já estou com versão 1.28.27

			window.dispatchEvent(new CustomEvent('__automaExecuteWorkflow', {detail: { 
				id: '8DSqeCvjHXm4AE1SZ59nH',
				data: {
					variables: {
						name: 'John Doe',
						search: 'Hello world'
					}
				} 
			}
OR

chrome-extension://infppggnoaenmfagbfknfkancpbljcca/execut.html#/8DSqeCvjHXm4AE1SZ59nH?name=value&search=10

**Comment by BenJamesAndo** [comment]
I kinda managed to pass a variable via a trigger URL. It seems you have to enter the value and then the variable. So instead of `?variableA=10` you have to do `?10=variableA`
It seems to only work with numbers and not letters. So `10` as a variable value works but `ten` doesn't. It kinda supports periods in the value, so `10.0` works but `.10` doesn't.

Then to get that variable in the workflow you need to do `{{variables.variableA}}` instead of `{{variables.$$variableA}}`

Should I open this as a separate bug report?

**Comment by eriksonssilva** [comment]
I have found out that if you encapsulate the string between double quotes, it will work! So instead of
chrome-extension://infppggnoaenmfagbfknfkancpbljcca/execute.html#/workflowId?variableA=value
you would do
chrome-extension://infppggnoaenmfagbfknfkancpbljcca/execute.html#/workflowId?"value"=variableA.
Not sure why it's like that, but at least it's a workaround!

**Comment by HuangKaibo2017** [comment]
can the workflow be called use this way? 
```
const url = automaFetData('activeTabUrl', ''); // I can get full url in js code block by this way
// get a variable named keyword value from the url:
function extractVariable(url) {
  // Create a URL object to easily parse the URL
  const urlObj = new URL(url);
  // Extract the 'keyword' parameter value
  const keyword = urlObj.searchParams.get('keyword');
  // Decode the percent-encoded keyword back to UTF-8
  const decodedKeyword = decodeURIComponent(keyword);
  return decodedKeyword;
}
const keyword = extractVariable(url);
```

**Comment by wumingluren** [comment]
> "value"=variableA.

This is the right thing to do. I don't know why it hasn't been fixed for so long.

**Comment by ghfFelix** [comment]
> > "value"=variableA.
> 
> This is the right thing to do. I don't know why it hasn't been fixed for so long.

yes, I tried many times to get it to work; here is the demo.

The first block is Trigger, which has no parameters. The second block is New Tab, and its URL is http://baidu.com/s?ie=UTF-8&wd={{variables.urlVariable}}. Then I press the URL: chrome-extension://infppggnoaenmfagbfknfkancpbljcca/execute.html#/3IpNbSlaB9w-9XYuK6m00?"手机"=urlVariable into Chrome, and it works.

Initially, in the New Tab block, I used the URL http://baidu.com/s?ie=UTF-8&wd={{urlVariable}}, then I entered chrome-extension://infppggnoaenmfagbfknfkancpbljcca/execute.html#/3IpNbSlaB9w-9XYuK6m00?"手机"=urlVariable into Chrome, but it didn’t work. Then, when I clicked "Finish" in the log, I found that the urlVariable was in the variables, and the format was:

{
  "referenceData": {
    "loopData": {},
    "variables": {
      "urlVariable": "手机"
    },
    "prevBlockData": ""
  }
}
So, I changed the URL in the New Tab block to http://baidu.com/s?ie=UTF-8&wd={{variables.urlVariable}}, and entered chrome-extension://infppggnoaenmfagbfknfkancpbljcca/execute.html#/3IpNbSlaB9w-9XYuK6m00?"手机"=urlVariable into Chrome, and then it worked as expected.
