### ISSUE TITLE
Automa Failed to Fetch Google Sheet

### ISSUE THREAD

**Issue by tvmorganas** [AutomaApp/automa#1855]
Google sheets function didn't work today ,
It works before, I used it to update data to goole spreadsheets

Already Shared with "[service@automa2.iam.gserviceaccount.com](mailto:service@automa2.iam.gserviceaccount.com)"

Here the log
1. Go to 'trigger.'
2. New tab was open
3. Google sheet " Failed to Fetch"

Yesterday cannot open the web but now it can.

Yesterday i try in somewhere (not my office) it works

**Comment by mohdlatif** [comment]
me too facing the same issue

even their website is not loading

**Comment by bingren-yd** [comment]
Apologies, due to the website domain name resolution update, some users have encountered issues when accessing automa.site.

You can try the following methods to resolve the issue:
1. Update your local DNS (use some public DNS resolution services, such as 233.5.5.5) (1.1.1.1 and 8.8.8.8 have not yet updated our website, so there might be issues).
2. Try to clear your browser's DNS cache (if using Chrome, you can open chrome://net-internals/#dns to attempt to clear it).
3. Refresh your local DNS cache (on Windows, you can enter ipconfig /flushdns in the cmd command to attempt to refresh it).

@mohdlatif @tvmorganas

**Comment by africano0101** [comment]
just wanted to show you an alternative method in case this issue happens again:

convert you table range into JSON format and paste into Automa

![Screenshot from 2024-11-05 15-56-34](https://github.com/user-attachments/assets/b1c1ad33-558e-4cfc-85c1-2c79722a51db)

**Comment by tvmorganas** [comment]
<img width="751" alt="image" src="https://github.com/user-attachments/assets/c634e610-3f39-4260-9e0d-981c68736ccf" />

how if i have frameworks like this

**Comment by africano0101** [comment]
sorry late reply, in your case I would suggest having a local table, rather than go to google sheet, try with "insert data"

![Image](https://github.com/user-attachments/assets/3490979e-1590-4121-8937-7c1a41210ca8)

**Comment by africano0101** [comment]
Sorry for the late reply, in your case I suggest one change, from google sheet to loop data in Json format.

**Comment by africano0101** [comment]
Sorry for the late reply, in your case I suggest disable "google sheet (data)". Convert table of your google sheet (data)" to JSON and place it where you have the "Loop Data (orders)".

Loop data
ID: orders
Loop through: Custom data
Insert data: (your converted table in JSON format)
