### ISSUE TITLE
Can't go back to previous page.

### ISSUE THREAD

**Issue by bomayso** [AutomaApp/automa#251]
When executing the script with automatic options.
Can't go back.
![image](https://user-images.githubusercontent.com/25388131/148576106-3d9e3b74-b53a-4a65-bf50-4bc1da004c65.png)
i open new tab with url https://github.com/Kholid060
then click on "automa", the url changes to https://github.com/Kholid060/automa
but can't go back https://github.com/Kholid060
![image](https://user-images.githubusercontent.com/25388131/148576500-32cea9f6-4da6-4308-bec3-97ae7ab0804b.png)

**Comment by Kholid060** [comment]
The **Go back** block doesn't work because the tab doesn't have a history.

![Untitled](https://user-images.githubusercontent.com/22908993/148637786-e36a3d68-7161-4baf-b376-a5c1ba1b7ee5.png)

I have tested workflow with the same flow that you have. And to be honest, I don't know why chrome have this behavior
