### ISSUE TITLE
repeat task make the same randomString twice

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#302]
![image](https://user-images.githubusercontent.com/20383505/151652449-5caa3885-8132-4c30-895f-c0df542689a8.png)

---javascript block code:----
function randomString(e) {  
  e = e || 32;
  var t = "ABCDEFGHJKMNPQRSTWXYZabcdefhijkmnprstwxyz2345678",
  a = t.length,
  n = "";
  for (i = 0; i < e; i++) n += t.charAt(Math.floor(Math.random() * a));
  return n
}
picname =  randomString(6)
automaNextBlock({picname})
---javascript block code:----

randomString(6)  as screensnap'name , when use repeat task block 
I find the first picture's randomstring  name  is the same as the second picture's name

**Comment by Kholid060** [comment]
Can you show the file name in the take screenshot block?

**Comment by whwh656** [comment]
> Can you show the file name in the take screenshot block?

I write {{dataColumns@column}}.jpeg  in the take screenshot block

![image](https://user-images.githubusercontent.com/20383505/151743262-7f1b4b21-93d8-4185-8bec-d44170c4522f.png)

**Comment by Kholid060** [comment]
> I write {{dataColumns@column}}.jpeg in the take screenshot block

`{{dataColumns@column}}` is actually a "shortcut" for `{{dataColumns@0.column}}`, which means it refers to the `column` column on the first row. That's why the screenshot file name is always the same, to fix this you can use the `prevBlockData` keyword to refer to the value that the javascript code block return. For example, `{{ prevBlockData@picname }}`

![image](https://user-images.githubusercontent.com/22908993/151747618-93a426a5-76c3-4c58-9072-451b511f26ce.png)
