### ISSUE TITLE
It doesn't seem very stable，pls have a check，thanks

### ISSUE THREAD

**Issue by Kathrie** [AutomaApp/automa#341]
Sometimes the execution succeeds, and sometimes the step is incomplete

The case：
![image](https://user-images.githubusercontent.com/98003000/153812921-df13205f-f5d2-4383-8c24-7e49382a03e4.png)

sometimes the step is incomplete：
![image](https://user-images.githubusercontent.com/98003000/153812880-60214ae7-60fb-4b0d-bc9b-7d1689dad615.png)

Sometimes the execution succeeds：
![image](https://user-images.githubusercontent.com/98003000/153813000-3955e226-8fa1-47f3-9bfc-aebede25e21d.png)

**Comment by Kholid060** [comment]
The workflow stops executing because the element you try to check using the "Element exist" block doesn't exist and it also doesn't have a fallback. To fix this, try to increase the "Try for" and the "Timeout" value

![image](https://user-images.githubusercontent.com/22908993/153846028-a804b850-2a10-4920-927b-2a7e4ab0b3f5.png)

**Comment by Kathrie** [comment]
It works after i  increase the "Try for" and the "Timeout" value and add a 500ms delay.Thanks.
