### ISSUE TITLE
"Update previously opened tab" not working

### ISSUE THREAD

**Issue by alfalfaw** [AutomaApp/automa#447]
**Describe the bug**
i have  checkout  the `Update previously opened tab` , but  still open a new tab.

**Expected behavior**
when i checkout `Update previously opened tab` , Automa will execute the workflow on an opened tab without refreshing page.

**Screenshots**
<img width="306" alt="image" src="https://user-images.githubusercontent.com/28943252/163313049-3ba6c196-c99f-42fa-a317-afbb898dcdc1.png">

**Comment by Kholid060** [comment]
The `Update previously opened tab` only works when the `new tab` block has the same workflow execution session. For example, when you have a workflow with two `new tab` blocks and in the second `new tab` block the `Update previously opened tab` option is enabled. Instead of creating a new tab, the second block will update the tab that was opened by the first block.

![image](https://user-images.githubusercontent.com/22908993/163511415-a0adbf0c-cc4d-413d-ae12-ec6b4974b292.png)

**Comment by q631263135** [comment]
What I encountered was the opening of the current tab, which I did using "Javascript Code Block "
