### ISSUE TITLE
希望增加一种数据类型

### ISSUE THREAD

**Issue by rain0002009** [AutomaApp/automa#747]
我发现table，variables，globalData都只能用JSON

现在我想在HTTP Request Block中使用form data，虽然有了这个选项了，但我无法获取数据

希望在Javascript Code Block中能设置form data，在HTTP Request Block中能获取form data

**Comment by Kholid060** [comment]
You can see the [documentation](https://docs.automa.site/blocks/webhook.html#form-data) on how to send form data in the HTTP request block.
If you want to set the [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) in the JS block, use those form data in the HTTP request, I don't think that's possible because the [method](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/sendMessage#parameters) that Automa uses to send the data from the JavaScript block doesn't support the FormData type.
