### ISSUE TITLE
An Error in Javascript Code Block.

### ISSUE THREAD

**Issue by standingflower0607** [AutomaApp/automa#748]
I want to stop my workflow when an error is thrown in Javascript Code Block.

**Comment by Kholid060** [comment]
Can you show me how you write the JS code? Because if you throw an error like this
![image](https://user-images.githubusercontent.com/22908993/187334604-aa44514b-dfce-4694-a67e-cd515902643e.png)

The workflow will automatically stop
![image](https://user-images.githubusercontent.com/22908993/187334667-2340f93a-c010-4e17-85b2-6f9677065f87.png)

**Comment by mzaini30** [comment]
I think, this issue has solved.

**Comment by standingflower0607** [comment]
Here is my code.
<img width="379" alt="キャプチャ" src="https://user-images.githubusercontent.com/40904182/187351557-7e9e087b-ca7a-485d-a130-af1fd33cae85.PNG">

I confirmed that the new error in the middle is throwed in chrome dev tools console, but it don't stop.
<img width="744" alt="キャプチャ2" src="https://user-images.githubusercontent.com/40904182/187351865-c3190d3f-5dbf-4604-997c-cf0893d774b3.PNG">

**Comment by Kholid060** [comment]
For now, I think you can modify the script like this

```js
let ticket_details = document.getElementsByClassName("has_detail");
let urls = [];
let isError = false;

for (let i = ticket_details.length - 1;  i > -1; i--) {
  let ticket_source = ticket_details[i].getElementsByClassName("ticket_");
  let url= ticket_source.nextElementSibling.href;
  let support_status = document.getElementsByClassName("has_detail")[i]

  if (ticket_source.childElementCount < 1) {
    if (support_status === '') {
       urls.push(url)
    } else {
       isError = true;
       break;
    }
  }
}

if (isError) throw new Error("Error");
```

**Comment by standingflower0607** [comment]
It worked! Thank you.
Since I'm begginer of coding, Could you explain why my code didn't work?

**Comment by Kholid060** [comment]
> It worked! Thank you. Since I'm a beginner at coding, Could you explain why my code didn't work?

Before injecting the code inside the JS block, Automa is wrapping it inside a try...catch statement like
```js
try {
  // your code
} catch (error) {
  // Automa error handler
}
```

And because of you handled the error by writing your own try...catch statement without throwing the error back in the `catch` block (https://github.com/AutomaApp/automa/issues/748#issuecomment-1231138563), Automa doesn't know if there's an error thrown inside your code.

And in this [comment](https://github.com/AutomaApp/automa/issues/748#issuecomment-1231151143), I think I might be wrong. You don't actually need to change the code, you only need to remove the try...catch statement inside your code.

**Comment by standingflower0607** [comment]
OK, I got it. Thank you for your prompt response.!
