### ISSUE TITLE
Looping doesn't work on several sites

### ISSUE THREAD

**Issue by gal064** [AutomaApp/automa#770]
**Describe the bug**
Looping doesn't work on several sites

**To Reproduce**
See video as example
https://user-images.githubusercontent.com/50427415/189191503-35f07dfa-40e7-469c-877f-6c10862279e3.mp4

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Extension Version: 1.18.1

**Additional context**
Tried also on Linkedin and Google search with same results. Only first item is saved

**Comment by Kholid060** [comment]
I think it's not working because your workflow (see below image) doesn't have a loop breakpoint
![image](https://user-images.githubusercontent.com/22908993/189292071-dd465517-5cea-4baa-ae42-8058317d8dd4.png)

after selecting a list of elements you must press escape so Automa knows when to put loop breakpoint in your workflow.

https://user-images.githubusercontent.com/22908993/189293195-ccdeac3b-eec2-4e2d-bf63-881e85834325.mp4
