### ISSUE TITLE
Would like to click only on visible elements

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#820]
I get this error :
`Failed to execute 'querySelectorAll' on 'Document': '#mybetsContainer > .betSrcCont span:visible.glyphicon' is not a valid selector`

when trying to run this selector:
`#mybetsContainer > .betSrcCont span:visible.glyphicon`

but it works fine in console on the page as:
`$("#mybetsContainer > .betSrcCont span:visible.glyphicon")`

I would like this `:visible` selector to work in Automata.

I'm using it on a Click block which is set to Multiple, so there are some shadow duplicate items that I don't want to click on, but they match exactly the same as the selector. So I want to add a visible filter to the results to be clicked on.

**Comment by Kholid060** [comment]
> I get this error : `Failed to execute 'querySelectorAll' on 'Document': '#mybetsContainer > .betSrcCont span:visible.glyphicon' is not a valid selector`
> 
> when trying to run this selector: `#mybetsContainer > .betSrcCont span:visible.glyphicon`

It's because the `:visible` pseudo-class is not valid, it's not listed in [the specification](https://www.w3.org/TR/selectors-4/)

> but it works fine in console on the page as:
> `$("#mybetsContainer > .betSrcCont span:visible.glyphicon")`

That page might be using jquery because the `:visible` pseudo-class is only available in [jquery](https://api.jquery.com/visible-selector/)

> I would like this `:visible` selector to work in Automata.
> 
> I'm using it on a Click block which is set to Multiple, so there are some shadow duplicate items that I don't want to click on, but they match exactly the same as the selector. So I want to add a visible filter to the results to be clicked on.

I think the only way to do that is by looping the elements using the loop elements block and then using the conditions block to check whether the element is visible or not.

![image](https://user-images.githubusercontent.com/22908993/194434375-19666bb2-b6ad-4792-b751-4f8552c591df.png)
![image](https://user-images.githubusercontent.com/22908993/194434397-29aed779-879e-4fc5-adba-b8fd19936c91.png)

**Comment by jddcef** [comment]
Thanks, that option was deep in the condition settings... glad you pointed it out for me. Cheers
