### ISSUE TITLE
Paramater prompt block - often gets stuck even if I continue

### ISSUE THREAD

**Issue by jddcef** [AutomaApp/automa#894]
Even though I press Continue on the parameter prompt, often it just waits for `workflow.blocks.parameter-prompt.name` in the logs until some timeout happens...
Seems like it doesn't inform the flow very reliably that something was pressed

**Comment by ooglek** [comment]
**EXPECTED**
Parameter Prompt with no values continues to the next block immediately after hitting `Continue`.

**ACTUAL**
Parameter Prompt with no values delays by 15-21 seconds AFTER hitting `Continue` before the next loop is executed.

**VERSION**: 1.23.3
**BROWSER**: Google Chrome on MacOS Version 107.0.5304.110 (Official Build) (x86_64)

I'm finding this as well in 1.23.3.

I have a simple workflow:

1. Trigger
2. Active Tab
3. Loop Data (List of search terms in JSON, e.g. `["term 1", "term 2", "term 3"]` currently 27 items in the list)
4. Element Exists
5. Form (inserts the value from Loop)
6. Press key (presses "enter" in that form element to submit)
7. Parameter Prompt (no input parameters, just a continue button, because I want the page to load, look at it, then when reviewed, hit "Continue" in Automa to go to the next form value. Timeout set to `0`
8. Loop Breakpoint

The first iteration, the logs show only 3 seconds from `Parameter Prompt` to `Loop Breakpoint`

However, the 2nd and subsequent loop, `Parameter Prompt` delays 21 seconds virtually every single time.

```
12:30:43 (0s) Trigger
12:30:43 (1s) Active tab
12:30:43 (0s) Loop data
12:30:43 (0s) Element exists
12:30:43 (0s) Forms Fill Search Form
12:30:44 (0s) Press key Search Execute
12:30:44 (3s) Parameter Prompt Next
12:30:47 (0s) Loop breakpoint 87j4oi
12:30:47 (0s) Loop data
12:30:47 (0s) Element exists
12:30:47 (0s) Forms Fill Search Form
12:30:47 (0s) Press key Search Execute
12:30:47 (21s) Parameter Prompt Next
12:31:08 (0s) Loop breakpoint 87j4oi
12:31:08 (0s) Loop data
12:31:08 (0s) Element exists
12:31:08 (0s) Forms Fill Search Form
12:31:08 (0s) Press key Search Execute
12:31:08 (21s) Parameter Prompt Next
12:31:29 (0s) Loop breakpoint 87j4oi
12:31:29 (0s) Loop data
12:31:29 (0s) Element exists
12:31:29 (0s) Forms Fill Search Form
12:31:29 (0s) Press key Search Execute
12:31:29 (21s) Parameter Prompt Next
```

**Comment by ooglek** [comment]
It looks like this is timeout related. When you set the Timeout to `0` it goes back to a "default value" of "20,000 ms" or 20 seconds. There does not seem to be a way to disable the timeout, and force the user to hit `Continue` for the flow to keep going. I can understand this, but it should be better documented.

https://github.com/AutomaApp/automa/blob/a92a3e84cd613b1ec6fdad922a440af3e77dda76/src/workflowEngine/blocksHandler/handlerParameterPrompt.js#L55

Additionally, repeated usages of Parameter Prompt seem to sit and wait for the entire set Timeout. I tried setting the timeout to 900 seconds and each subsequent use of Parameter Prompt in a loop caused a 900 second delay after the first. While I suspect that Parameter Prompt was maybe only tested as an initial portion of an automation, I'm using it as a way to pause and continue. 

Is there another preferred way to load a page, pause, and continue when I click?

I suspect the problem is found in `function getInputtedParams`

https://github.com/AutomaApp/automa/blob/a92a3e84cd613b1ec6fdad922a440af3e77dda76/src/workflowEngine/blocksHandler/handlerParameterPrompt.js#L4-L31

I suspect this is an order of operations problem.

`timeout` is `null` at line 6.

`timeout` is still `null` at line 12 when the `storageListener` is created. It is not the current timeoutID.

`timeout` is instantiated at line 24, but since `storageListener` exists in memory already, the `timeout` value is not somehow magically updated nor passed. So I suspect it is not clearing the timeout, as the ID is not really stored anywhere.
