### ISSUE TITLE
loop  data 

### ISSUE THREAD

**Issue by whwh656** [AutomaApp/automa#967]
![image](https://user-images.githubusercontent.com/20383505/204270587-9ca9f91f-da83-4d06-9258-29966df9e476.png)
![image](https://user-images.githubusercontent.com/20383505/204270766-cccb2de3-b712-4be3-8e23-357d9d95fa48.png)

i want to loopData.loopid.$index from 1 start but it start from 0

**Comment by Kholid060** [comment]
Try updating Automa to the latest version

**Comment by Kholid060** [comment]
Can you screenshot the loop data block that you have in your workflow? Because on the image you provided, the loop through selection in the loop data block says "Elements" but the data on the log data is a number which is supposed to a text like this
![image](https://user-images.githubusercontent.com/22908993/205270075-2152b200-7cd0-47ef-9ab3-4d80d0b469da.png)

**Comment by whwh656** [comment]
i want to click first page and then click second page 
loop block select element .number  index from 1 to 3

![image](https://user-images.githubusercontent.com/20383505/205279495-3c3bdf38-781f-438c-adb9-419c38b68e22.png)
click blcok .number:nth-child({{ loopData.K5cGeG.$index }})
![image](https://user-images.githubusercontent.com/20383505/205279771-996b77cf-5a44-49e7-9cad-c09351b5b7dc.png)
[xiala.txt](https://github.com/AutomaApp/automa/files/10140572/xiala.txt)

**Comment by Kholid060** [comment]
Try to use `.el-pager > li.number` as the selector on the loop data block, and in the click element block, use `{{ loopData.K5cGeG }}` as the selector.

**Comment by whwh656** [comment]
> .el-pager > li.number

![Uploading 截屏2022-12-03 下午5.46.38.png…]()
